const index = require('./index.js');
const unirest = require('unirest');

function test() {
    console.log("Printing this from urban.js");
}

function prepareData(str, msg) {
    var splitted = str.split(" "); 
    var modifiedStr = splitted.splice(2, splitted.length-3).join(" ");
    fetchData(modifiedStr, msg);
}

function fetchData(str, msg) { // code generated by rapid api 
    console.log(`Searching definition for ${str}`);
    var req = unirest("GET", "https://mashape-community-urban-dictionary.p.rapidapi.com/define");

    req.query({
        "term": str
    });
    var Keys = require('./keys.json'); // use keys to get rapidapi_key
    req.headers({
        "x-rapidapi-key": Keys.rapidapi_key,
        "x-rapidapi-host": "mashape-community-urban-dictionary.p.rapidapi.com",
        "useQueryString": true
    });
    req.end(function (res) {
        if (res.error) throw new Error(res.error);
        callback(res.body, msg);
    });
}

function removeSquareBrackets(str) {
    console.log(str);
    str = str.replace(']', '').replace('[', ''); // get rid of [ and ] in urban dict response // THERES PROBABLY A BETTER WAY TO DO THIS
    return str;
}

const callback = async(data, msg) => {
    var response = await(data);
    if (response != undefined) {
        response = response.list[0].definition; // get the first definition 
        response = removeSquareBrackets(response); // remove square brackets from the string
        if (response.length >= 2000) { // discord doesnt allow anything longer than 2000 characters
            response = response.substr(0, 1500);
        }
        index.sendMessage(msg, response); // send response
    }
    return null;
}

module.exports.test = test;
module.exports.primary = prepareData;